propel:
  _attributes:
    package: plugins.AxisMaterializedPathRepositoryPlugin.lib.Axis.MaterializedPath.Model

  axis_materialized_path_entry:
    _attributes: { phpName: Entry, namespace: Axis\MaterializedPath\Model }
    _propel_behaviors:
      symfony:
        form:   false
        filter: false

    id: ~

    entity_type: { type: varchar, size: 32, required: true }
    entity_id:   { type: varchar, required: true }

    slug: { type: varchar, required: true }
    path: { type: varchar, required: true }
    level: { type: varchar, required: true }
    order_number: { type: integer, default: 0 }

    _uniques:
      entity_path_uniq: [ entity_type, path ]